---
- hosts: all
  become: true
  vars:
    project_local_path: ~/devops_course/DevopsCalculator
    project_vagrant_path: ~vagrant/DevopsCalculator
  vars_files:
  - vars.yml

  roles:
  - role: ../roles/apt_update
  - role: ../roles/public_key
  - role: ../roles/jdk
  - role: ../roles/tomcat
  - role: ../roles/postgresql
  - role: ../roles/selenium_firefox

  tasks:
