---
- hosts: all
  become: true
  vars:
    tomcat_apps_path: /var/lib/tomcat8/webapps
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  tasks:
  - name: Copy public key
    copy: src=~/.ssh/id_rsa_devops_course.pub dest=~vagrant/.ssh/me.pub
  - shell: cat ~vagrant/.ssh/me.pub
    register: public_key
  - lineinfile:
      path: ~vagrant/.ssh/authorized_keys
      line: "{{public_key.stdout}}"
  - name: Install Tomcat 8
    apt: name=tomcat8 state=present
  - name: Ensure Tomcat 8 is started and enabled on boot
    service: name=tomcat8 state=started enabled=yes
  - name: Install PostgreSQL
    apt: name=postgresql,python3-dev,python3-psycopg2 state=present
  - name: Ensure PostgreSQL is started and enabled on boot
    service: name=postgresql state=started enabled=yes
  - name: Ensure PostgreSQLlocales are present
    locale_gen: name='en_US.UTF-8' state=present

  - name: Create user, set MD5-hashed password, grant privs
    postgresql_user:
      name: admin
      password: md51a1dc91c907325c69271ddf0c944bc72
      role_attr_flags: CREATEDB,NOSUPERUSER
#
#  - name: Ensure database is created
#    sudo_user: postgres
#    postgresql_db: name=admin
#               encoding='UTF-8'
#               lc_collate='en_US.UTF-8'
#               lc_ctype='en_US.UTF-8'
#               state=present
#
#  - name: Ensure user has access to the database
#    sudo_user: postgres
#    postgresql_user: db=history
#                 name=admin
#                 password=pass
#                 priv=ALL
#                 state=present

#- name: Create test_table with several columns in ssd tablespace with fillfactor=10 and autovacuum_analyze_threshold=1
#  postgresql_table:
#    name: test_table
#    columns:
#    - id bigserial primary key
#    - num bigint
#    - stories text
#    tablespace: ssd
#    storage_params:
#    - fillfactor=10
#    - autovacuum_analyze_threshold=1

