# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "env-prod"

  config.vm.network "private_network", ip: "192.168.12.3"
  config.vm.network "forwarded_port", guest: 8080, host: 12003

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

 # config.vm.provision "file", source: "~/.ssh/id_rsa_devops_course.pub", destination: "~vagrant/.ssh/me.pub"
 # config.vm.provision "shell", inline: "cat ~vagrant/.ssh/me.pub >> ~vagrant/.ssh/authorized_keys"

  config.vm.provision "ansible" do |ansible|
     ansible.compatibility_mode = "2.0"
     ansible.playbook = "playbook.yml"
  end

end
