- name: Copy public key
  copy: src=~/.ssh/id_rsa_devops_course.pub dest=~root/.ssh/me.pub
- shell: cat ~root/.ssh/me.pub
  register: public_key
- lineinfile:
    path: ~root/.ssh/authorized_keys
    line: "{{public_key.stdout}}"
