- name: Install PostgreSQL
  apt: name=postgresql,python3-dev,python3-psycopg2 state=present
- name: Ensure PostgreSQL is started and enabled on boot
  service: name=postgresql state=started enabled=yes
- name: Ensure PostgreSQLlocales are present
  locale_gen: name='en_US.UTF-8' state=present

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db: name=postgres encoding=UTF-8 state=present #lc_collate=en_US.UTF-8 lc_ctype=en_US.UTF-8
- name: Create user, grant privs
  become: true
  become_user: postgres
  postgresql_user: name=admin password="1a1dc91c907325c69271ddf0c944bc72" encrypted=yes role_attr_flags=CREATEDB,NOSUPERUSER
- name: Create 'history' table
  become_user: postgres
  postgresql_table:
    name: history
    db: postgres
    owner: admin
    columns:
    - ts TIMESTAMP PRIMARY KEY
    - record VARCHAR (50) NOT NULL
