---
- hosts: all
  become: true
  vars_files:
  - vars.yml

  roles:
  - role: ../roles/apt_update
  - role: ../roles/jdk
  - role: ../roles/tomcat
  - role: ../roles/postgresql
  - role: ../roles/selenium_firefox
